/* Hands on 3 23/4/2018 */
/* 2.3 */

/* 1. */

/* True */

/* 2. */

/* False */

/* 3. */

/* 
SELECT MAX(SALARY) MAXINUM, MIN(SALARY) MINIMUN, SUM(SALARY) SUM, AVG(SALARY) AVERAGE
FROM EMPLOYEES;
*/

/* 4. */

SELECT MAX(SALARY) MAXINUM, MIN(SALARY) MINIMUN, SUM(SALARY) SUM, AVG(SALARY) AVERAGE, JOB_ID
FROM EMPLOYEES
GROUP BY JOB_ID;

/* 5. */

SELECT JOB_ID, COUNT(*)
FROM EMPLOYEES
GROUP BY JOB_ID;

/* 6. */

SELECT COUNT(DISTINCT manager_id) AS "Number of Managers"
FROM EMPLOYEES;

/* 7. */

SELECT (MAX(SALARY) - MIN(SALARY)) AS DIFFERENCE
FROM EMPLOYEES;

/* 8. */
SELECT MANAGER_ID, MIN(SALARY)
FROM EMPLOYEES
GROUP BY MANAGER_ID
HAVING MIN(SALARY) > 6000 AND MANAGER_ID IS NOT NULL
ORDER BY MIN(SALARY);

/* 9. */
SELECT COUNT(EMPLOYEE_ID) AS "NUMBER_OF_EMPLOYEES", EXTRACT(YEAR FROM HIRE_DATE) AS THE_YEAR
FROM EMPLOYEES 
GROUP BY EXTRACT(YEAR FROM HIRE_DATE)
HAVING EXTRACT(YEAR FROM HIRE_DATE) BETWEEN 2005 AND 2008;
