/* Hands on 3 23/4/2018 */
/* 2.4 */

/* 1. */
SELECT LOCATIONS.LOCATION_ID,LOCATIONS.STREET_ADDRESS, LOCATIONS.CITY, LOCATIONS.STATE_PROVINCE, COUNTRIES.COUNTRY_NAME
FROM LOCATIONS NATURAL JOIN COUNTRIES;

/* 2. */
SELECT LAST_NAME, DEPARTMENT_ID, DEPARTMENT_NAME
FROM DEPARTMENTS  NATURAL JOIN EMPLOYEES e;

/* 3. */
SELECT LAST_NAME, JOB_ID, DEPARTMENT_ID, DEPARTMENT_NAME
FROM EMPLOYEES NATURAL JOIN DEPARTMENTS NATURAL JOIN LOCATIONS;

/* 4. */
SELECT e.LAST_NAME AS "Employee", e.EMPLOYEE_ID AS "Emp#", e2.LAST_NAME AS "Manager", e.MANAGER_ID AS "Mng#"
FROM EMPLOYEES e
JOIN EMPLOYEES e2
ON e.MANAGER_ID = e2.EMPLOYEE_ID;

/* 5. */
SELECT e.LAST_NAME AS "Employee", e.EMPLOYEE_ID AS "Emp#", e2.LAST_NAME AS "Manager", e.MANAGER_ID AS "Mng#"
FROM EMPLOYEES e
LEFT OUTER JOIN EMPLOYEES e2
ON e.MANAGER_ID = e2.EMPLOYEE_ID
ORDER BY e.EMPLOYEE_ID;

/* 6. */
SELECT e.LAST_NAME AS EMPLOYEE, e.HIRE_DATE AS EMPLOYEE_HIRE_DATE, e_.LAST_NAME AS MANAGER, e_.HIRE_DATE AS MANAGER_HIRE_DATE
FROM EMPLOYEES e
JOIN EMPLOYEES e_
ON e.MANAGER_ID = e_.EMPLOYEE_ID
WHERE e.HIRE_DATE < e_.HIRE_DATE;

